# Splunk file monitor input for Mini SOC Lab

[monitor://C:\\Users\\Hardee\\OneDrive\\Documents\\Playground\\mini-soc-lab\\data\\security_events.jsonl]
disabled = false
sourcetype = mini_soc:json
index = main
crcSalt = <SOURCE>